.TH ODYNCASH-CLI "1" "November 2016" "odyncash-cli 1.0"
.SH NAME
odyncash-cli \- a remote procedure call client for OdynCash.
.SH SYNOPSIS
odyncash-cli [options] <command> [params] \- Send command to OdynCash.
.TP
odyncash-cli [options] help \- Asks OdynCash for a list of supported commands.
.SH DESCRIPTION
This manual page documents the odyncash-cli program. odyncash-cli is an RPC client used to send commands to OdynCash.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
